<center><h1 style="color:#D4AF37"> ⚡⚡ AEMR Data Analysis ⚡⚡</h1>

<img src = "https://images.squarespace-cdn.com/content/v1/551972d8e4b0d571edc2e2c8/8f3abd33-0916-4415-9b24-593eea1d1e3c/Screen+Shot+2022-04-20+at+12.41.24+PM.png">

  
It’s time for you to apply your budding SQL Competencies to analyse data for the American Energy Market Regulator (AEMR).

The analytics team has supplied you with the following table extract that contains all the data you need to analyse for the `AEMR` outages. 

<li> AEMR_Outage_Table </li> 
    
Now let's revisit the business problem below and understand what we're seeking to solve.

<h1 style="color:#D4AF37"> What's the Business Problem? 💰</h1>

The American Energy Market Regulator (AEMR) is responsible for looking after the
United States of America’s domestic energy network. The regulator’s responsibility is to
ensure that America’s energy network remains reliable with minimal disruptions, which
are known as outages. 

There are four key types of outages:

● Consequential

● Forced 

● Opportunistic 

● Planned 

Recently, the AEMR management team has been increasingly aware of a large number
of energy providers that submitted outages over the 2016 and 2017 calendar years. The
management team has expressed a desire to have the following two areas of concern
addressed:

<b> A) Energy Stability and Market Outages
    <p>
B) Energy Losses and Market Reliability </b>

As an analyst within the data and reporting team, you have been asked to address these
two immediate areas of concern. Feel free to also explore beyond the queries asked and provide additional insights that you feel may be of interest to the management team. 

<h3 style="color:#D4AF37">  SQLite Refresher ⚙️ </h3>

We've pre-loaded the data you need to access in the `AEMR.db` we've included. We'll have you write SQL below where all your SQL queries will be stored in this notebook as a reference you can use when you review your data analysis in Tableau. </b>.

To load the `AEMR.db` file into this notebook, run the below cells.

<b> ⚠️ Please remember that everytime you close this file and re-open this, you'll need to re-run the cells below. ⚠️ </b>

<b>⚠️ Note: Remember, you'll need to start each cell with the **`%%sql`** line, which allows us to execute SQL from within this notebook.</b>

In [1]:
%%capture
!pip install ipython-sql sqlalchemy
import sqlalchemy
sqlalchemy.create_engine("sqlite:///AEMR.db")
%load_ext sql
%sql sqlite:///AEMR.db

In [2]:
%%js
require(['notebook/js/codecell'], function (codecell) {
    codecell.CodeCell.options_default.highlight_modes['magic_text/x-mssql'] = { 'reg': [/%?%sql/] };
    Jupyter.notebook.events.one('kernel_ready.Kernel', function () {
        Jupyter.notebook.get_cells().map(function (cell) {
            if (cell.cell_type == 'code') { cell.auto_highlight(); }
        });
    });
});

<IPython.core.display.Javascript object>

We've included an example of how you would write a query against the database below:

~~~sql
%%sql
SELECT
*
FROM AEMR_Outage_Table
LIMIT 10
~~~

Once you've written your SQL, you'll then need to press `Ctrl` + `Enter` to run the cell.
Otherwise, you can just press `run` at the very top of your screen, to run the specific cell.

For your convenience, we've included a <b style = "color:#5D3FD3"> subset of the answers </b> under the header `Expected Output (Sample)`. These small subsets also include all the `columns` you'll need to include in your Query, so you know what to expect!

Good luck!

<b>PS: In case any of you get stuck regarding how to tackle any of the questions, we've included a breakdown <a href = "https://drive.google.com/file/d/1sXBGV5MZooZ7L38WYyXf9lIaA5sdKL7X/view?usp=share_link"> here</a> where Chris walks through how to tackle each question! Feel free to use this when you're stuck and you can't book a Mentor Call! </b>

<h3 style="color:#D4AF37"> ⚡ Part I. Energy Stability & Market Outages ⚡ </h3>

Energy stability is one of the key themes the AEMR management team cares about. To ensure energy security and reliability, AEMR needs to understand the following:
<p>
<b>

<li> What are the most common outage types and how long do they tend to last? 
<li> How frequently do the outages occur? 
<li> Are there any energy providers which have more outages than their peers which may be indicative of being unreliable? 
    
<p>

<u style="color:Maroon"> Please note that throughout the entire case study, we are interested ONLY in the Outages where Status = Approved. We don't have any interest in Outages that were cancelled or not approved. This means your WHERE Clause will ALWAYS contain the field `Where Status = Approved` </u>

<h3 style="color:#D4AF37"> Question One </h3> 

<b> Write a SQL Statement to `COUNT` the number of valid (i.e. `Status = Approved`) Outage Events sorted by their respective `Outage_Reason` (i.e. `Forced`, `Consequential`, `Scheduled`, `Opportunistic`) over the 2016 & 2017 Periods. </b>

Do we notice anything regarding the trends for specific Outages over the 2016 / 2017 Period?

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

<b>⚠️ Note: Remember, you'll need to start each cell with the **`%%sql`** line, which allows us to execute SQL from within this notebook.</b>

In [3]:
%%sql
SELECT
    COUNT(*) AS Total_Number_Outages,
    Outage_Reason,
    Year
FROM 
    AEMR_Outage_Table
WHERE 
    Status = 'Approved'
GROUP BY 
    Outage_Reason, Year

 * sqlite:///AEMR.db
Done.


[(181, 'Consequential', 2016),
 (127, 'Consequential', 2017),
 (1264, 'Forced', 2016),
 (1622, 'Forced', 2017),
 (106, 'Opportunistic Maintenance (Planned)', 2016),
 (102, 'Opportunistic Maintenance (Planned)', 2017),
 (380, 'Scheduled (Planned)', 2016),
 (320, 'Scheduled (Planned)', 2017)]

The data shows that forced outages happen the most, and they increased from 2016 to 2017. The other types of outages decreased in 2017. Planned outages, like maintenance and scheduled events, happened less often. This tells us that it must be hard to deal with unexpected problems

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(181, 'Consequential', 2016),
 (1264, 'Forced', 2016),
 (106, 'Opportunistic Maintenance (Planned)', 2016),
 (380, 'Scheduled (Planned)', 2016)]

Now how about examining some monthly trends? Do we note any behaviours across the months that indicate certain months having more reliability issues over other months? 


<h3 style="color:#D4AF37"> Question Two </h3>



<b> i) Write a SQL Statement showing the `Total` of all Outage Types (Forced, Consequential, Scheduled, Opportunistic) where the `Status = Approved`, that occurred for both 2016 and 2017, grouped by `Year` and `Month`.  per month (i.e. 1 – 12). Order by `Year`, `Month`, `Total_Number_Outages` in Descending Order.


ii) Building on the query you write in i), group the results by `Outage Type`, `Year` and `Month`. This is so you can identify whether there is any outage type specifically increasing on a monthly basis when comparing 2016 to 2017. </b>


<b>⚠️Hint: You might find it helpful to create a small Common Table Expression to address these two questions! </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [4]:
%%sql
SELECT Year,
        Month,
        COUNT(*) AS Total_Number_Outages,
        Outage_Reason
FROM AEMR_Outage_Table
WHERE Status = 'Approved'
GROUP BY Outage_Reason, Year, Month
ORDER BY Year, Month, Total_Number_Outages DESC

 * sqlite:///AEMR.db
Done.


[(2016, 1, 134, 'Forced'),
 (2016, 1, 24, 'Consequential'),
 (2016, 1, 24, 'Scheduled (Planned)'),
 (2016, 1, 9, 'Opportunistic Maintenance (Planned)'),
 (2016, 2, 149, 'Forced'),
 (2016, 2, 43, 'Scheduled (Planned)'),
 (2016, 2, 23, 'Consequential'),
 (2016, 2, 12, 'Opportunistic Maintenance (Planned)'),
 (2016, 3, 94, 'Forced'),
 (2016, 3, 21, 'Scheduled (Planned)'),
 (2016, 3, 14, 'Opportunistic Maintenance (Planned)'),
 (2016, 3, 7, 'Consequential'),
 (2016, 4, 86, 'Forced'),
 (2016, 4, 45, 'Scheduled (Planned)'),
 (2016, 4, 3, 'Opportunistic Maintenance (Planned)'),
 (2016, 5, 101, 'Forced'),
 (2016, 5, 36, 'Consequential'),
 (2016, 5, 33, 'Scheduled (Planned)'),
 (2016, 5, 4, 'Opportunistic Maintenance (Planned)'),
 (2016, 6, 112, 'Forced'),
 (2016, 6, 30, 'Scheduled (Planned)'),
 (2016, 6, 14, 'Opportunistic Maintenance (Planned)'),
 (2016, 6, 12, 'Consequential'),
 (2016, 7, 80, 'Forced'),
 (2016, 7, 31, 'Scheduled (Planned)'),
 (2016, 7, 23, 'Consequential'),
 (2016, 7, 13, 'Opportunistic Maintenance (Planned)'),
 (2016, 8, 152, 'Forced'),
 (2016, 8, 29, 'Scheduled (Planned)'),
 (2016, 8, 7, 'Opportunistic Maintenance (Planned)'),
 (2016, 8, 6, 'Consequential'),
 (2016, 9, 96, 'Forced'),
 (2016, 9, 16, 'Scheduled (Planned)'),
 (2016, 9, 11, 'Opportunistic Maintenance (Planned)'),
 (2016, 9, 1, 'Consequential'),
 (2016, 10, 67, 'Forced'),
 (2016, 10, 37, 'Scheduled (Planned)'),
 (2016, 10, 15, 'Consequential'),
 (2016, 10, 5, 'Opportunistic Maintenance (Planned)'),
 (2016, 11, 127, 'Forced'),
 (2016, 11, 41, 'Scheduled (Planned)'),
 (2016, 11, 25, 'Consequential'),
 (2016, 11, 7, 'Opportunistic Maintenance (Planned)'),
 (2016, 12, 66, 'Forced'),
 (2016, 12, 30, 'Scheduled (Planned)'),
 (2016, 12, 9, 'Consequential'),
 (2016, 12, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 1, 70, 'Forced'),
 (2017, 1, 12, 'Consequential'),
 (2017, 1, 12, 'Scheduled (Planned)'),
 (2017, 1, 9, 'Opportunistic Maintenance (Planned)'),
 (2017, 2, 97, 'Forced'),
 (2017, 2, 27, 'Consequential'),
 (2017, 2, 20, 'Scheduled (Planned)'),
 (2017, 2, 6, 'Opportunistic Maintenance (Planned)'),
 (2017, 3, 53, 'Forced'),
 (2017, 3, 30, 'Scheduled (Planned)'),
 (2017, 3, 19, 'Consequential'),
 (2017, 3, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 4, 73, 'Forced'),
 (2017, 4, 34, 'Scheduled (Planned)'),
 (2017, 4, 12, 'Consequential'),
 (2017, 4, 8, 'Opportunistic Maintenance (Planned)'),
 (2017, 5, 105, 'Forced'),
 (2017, 5, 47, 'Scheduled (Planned)'),
 (2017, 5, 9, 'Opportunistic Maintenance (Planned)'),
 (2017, 5, 5, 'Consequential'),
 (2017, 6, 172, 'Forced'),
 (2017, 6, 17, 'Scheduled (Planned)'),
 (2017, 6, 8, 'Consequential'),
 (2017, 6, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 7, 182, 'Forced'),
 (2017, 7, 22, 'Scheduled (Planned)'),
 (2017, 7, 5, 'Opportunistic Maintenance (Planned)'),
 (2017, 7, 1, 'Consequential'),
 (2017, 8, 170, 'Forced'),
 (2017, 8, 23, 'Scheduled (Planned)'),
 (2017, 8, 14, 'Opportunistic Maintenance (Planned)'),
 (2017, 8, 2, 'Consequential'),
 (2017, 9, 137, 'Forced'),
 (2017, 9, 18, 'Scheduled (Planned)'),
 (2017, 9, 10, 'Consequential'),
 (2017, 9, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 10, 207, 'Forced'),
 (2017, 10, 50, 'Scheduled (Planned)'),
 (2017, 10, 11, 'Consequential'),
 (2017, 10, 8, 'Opportunistic Maintenance (Planned)'),
 (2017, 11, 145, 'Forced'),
 (2017, 11, 27, 'Scheduled (Planned)'),
 (2017, 11, 16, 'Opportunistic Maintenance (Planned)'),
 (2017, 11, 9, 'Consequential'),
 (2017, 12, 211, 'Forced'),
 (2017, 12, 20, 'Scheduled (Planned)'),
 (2017, 12, 11, 'Consequential'),
 (2017, 12, 6, 'Opportunistic Maintenance (Planned)')]

Most common outages are Forced outages and there seems they lost 50-250 days, which is highest in all outage types

In [5]:
%%sql
SELECT Year,
        Month,
        COUNT(*) AS Total_Number_Outages,
        Outage_Reason
FROM AEMR_Outage_Table
WHERE Status = 'Approved'
GROUP BY Outage_Reason, Year, Month
ORDER BY Year, Month, Total_Number_Outages DESC

 * sqlite:///AEMR.db
Done.


[(2016, 1, 134, 'Forced'),
 (2016, 1, 24, 'Consequential'),
 (2016, 1, 24, 'Scheduled (Planned)'),
 (2016, 1, 9, 'Opportunistic Maintenance (Planned)'),
 (2016, 2, 149, 'Forced'),
 (2016, 2, 43, 'Scheduled (Planned)'),
 (2016, 2, 23, 'Consequential'),
 (2016, 2, 12, 'Opportunistic Maintenance (Planned)'),
 (2016, 3, 94, 'Forced'),
 (2016, 3, 21, 'Scheduled (Planned)'),
 (2016, 3, 14, 'Opportunistic Maintenance (Planned)'),
 (2016, 3, 7, 'Consequential'),
 (2016, 4, 86, 'Forced'),
 (2016, 4, 45, 'Scheduled (Planned)'),
 (2016, 4, 3, 'Opportunistic Maintenance (Planned)'),
 (2016, 5, 101, 'Forced'),
 (2016, 5, 36, 'Consequential'),
 (2016, 5, 33, 'Scheduled (Planned)'),
 (2016, 5, 4, 'Opportunistic Maintenance (Planned)'),
 (2016, 6, 112, 'Forced'),
 (2016, 6, 30, 'Scheduled (Planned)'),
 (2016, 6, 14, 'Opportunistic Maintenance (Planned)'),
 (2016, 6, 12, 'Consequential'),
 (2016, 7, 80, 'Forced'),
 (2016, 7, 31, 'Scheduled (Planned)'),
 (2016, 7, 23, 'Consequential'),
 (2016, 7, 13, 'Opportunistic Maintenance (Planned)'),
 (2016, 8, 152, 'Forced'),
 (2016, 8, 29, 'Scheduled (Planned)'),
 (2016, 8, 7, 'Opportunistic Maintenance (Planned)'),
 (2016, 8, 6, 'Consequential'),
 (2016, 9, 96, 'Forced'),
 (2016, 9, 16, 'Scheduled (Planned)'),
 (2016, 9, 11, 'Opportunistic Maintenance (Planned)'),
 (2016, 9, 1, 'Consequential'),
 (2016, 10, 67, 'Forced'),
 (2016, 10, 37, 'Scheduled (Planned)'),
 (2016, 10, 15, 'Consequential'),
 (2016, 10, 5, 'Opportunistic Maintenance (Planned)'),
 (2016, 11, 127, 'Forced'),
 (2016, 11, 41, 'Scheduled (Planned)'),
 (2016, 11, 25, 'Consequential'),
 (2016, 11, 7, 'Opportunistic Maintenance (Planned)'),
 (2016, 12, 66, 'Forced'),
 (2016, 12, 30, 'Scheduled (Planned)'),
 (2016, 12, 9, 'Consequential'),
 (2016, 12, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 1, 70, 'Forced'),
 (2017, 1, 12, 'Consequential'),
 (2017, 1, 12, 'Scheduled (Planned)'),
 (2017, 1, 9, 'Opportunistic Maintenance (Planned)'),
 (2017, 2, 97, 'Forced'),
 (2017, 2, 27, 'Consequential'),
 (2017, 2, 20, 'Scheduled (Planned)'),
 (2017, 2, 6, 'Opportunistic Maintenance (Planned)'),
 (2017, 3, 53, 'Forced'),
 (2017, 3, 30, 'Scheduled (Planned)'),
 (2017, 3, 19, 'Consequential'),
 (2017, 3, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 4, 73, 'Forced'),
 (2017, 4, 34, 'Scheduled (Planned)'),
 (2017, 4, 12, 'Consequential'),
 (2017, 4, 8, 'Opportunistic Maintenance (Planned)'),
 (2017, 5, 105, 'Forced'),
 (2017, 5, 47, 'Scheduled (Planned)'),
 (2017, 5, 9, 'Opportunistic Maintenance (Planned)'),
 (2017, 5, 5, 'Consequential'),
 (2017, 6, 172, 'Forced'),
 (2017, 6, 17, 'Scheduled (Planned)'),
 (2017, 6, 8, 'Consequential'),
 (2017, 6, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 7, 182, 'Forced'),
 (2017, 7, 22, 'Scheduled (Planned)'),
 (2017, 7, 5, 'Opportunistic Maintenance (Planned)'),
 (2017, 7, 1, 'Consequential'),
 (2017, 8, 170, 'Forced'),
 (2017, 8, 23, 'Scheduled (Planned)'),
 (2017, 8, 14, 'Opportunistic Maintenance (Planned)'),
 (2017, 8, 2, 'Consequential'),
 (2017, 9, 137, 'Forced'),
 (2017, 9, 18, 'Scheduled (Planned)'),
 (2017, 9, 10, 'Consequential'),
 (2017, 9, 7, 'Opportunistic Maintenance (Planned)'),
 (2017, 10, 207, 'Forced'),
 (2017, 10, 50, 'Scheduled (Planned)'),
 (2017, 10, 11, 'Consequential'),
 (2017, 10, 8, 'Opportunistic Maintenance (Planned)'),
 (2017, 11, 145, 'Forced'),
 (2017, 11, 27, 'Scheduled (Planned)'),
 (2017, 11, 16, 'Opportunistic Maintenance (Planned)'),
 (2017, 11, 9, 'Consequential'),
 (2017, 12, 211, 'Forced'),
 (2017, 12, 20, 'Scheduled (Planned)'),
 (2017, 12, 11, 'Consequential'),
 (2017, 12, 6, 'Opportunistic Maintenance (Planned)')]

Last six months (July-Dec) showing higher numbers in both year compared to first six months (Jan-Jun).

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(2016, 1, 191),
 (2016, 2, 227),
 (2016, 3, 136),
 (2016, 4, 134),
 (2016, 5, 174)]

Hmm. Interesting. We've now identified a specific outage type is rapidly increasing from 2016 to 2017. However, frequency is just one aspect we care about. We also care about the <b> `duration` </b> of our ouatges.

In other words, if an outage is very short, we aren't as concerned. However, if the outage is very long, this then has the risk of threatening our energy supplies. We want to identify the problematic energy providers here. This leads us to our next question below. 

<h3 style="color:#D4AF37"> Question Three </h3>


<b>Write a SQL statement that calculates 1) The `Total_Number_Outage_Events` and 2) The <b> `Average Duration`</b> in <u>DAYS</u> for each `Participant Code` and `Outage Type` over the 2016 and 2017 Period where the `Status = Approved`. 
Order by `Total_Number_Outage_Events` in Descending Order, `Reason` and `Year`.
    
Please note the average duration in days should be rounded to 2 decimal places for ease of comparison. When calculating the average duration, please note that you'll need to use the following fields:

`Start_Time` and `End_Time`. </b>

<b>⚠️ Hint:</b> If you're not sure how to calculate the difference between the `start_time` and `end_time` , reference this link <a href ="https://learnsql.com/cookbook/how-to-calculate-the-difference-between-two-timestamps-in-sqlite/"> here </a>

We've included an example below of how you could use the `JULIANDAY()` function! Remember, the `JULIANDAY()` function returns the results in days, including the fractional component. Some of the date(s) are flipped in the dataset, so you'll need to use the ABS() function to ensure you don't return any negative values!

~~~sql
%%sql

SELECT
        AVG((ABS(JULIANDAY(Date_2) - JULIANDAY(Date1))) 
FROM Some_Database
~~~



<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [6]:
%%sql
SELECT
    Participant_Code,
    Outage_Reason,
    Year,
    COUNT(*) AS Total_Number_Outage_Events,
    ROUND(AVG(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) AS Average_Outage_Duration_In_Days
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved'
GROUP BY
    Participant_Code, Outage_Reason, Year
ORDER BY
    Total_Number_Outage_Events DESC,
    Outage_Reason,
    Year


 * sqlite:///AEMR.db
Done.


[('AURICON', 'Forced', 2017, 490, 0.07),
 ('GW', 'Forced', 2016, 317, 0.38),
 ('GW', 'Forced', 2017, 227, 1.06),
 ('AURICON', 'Forced', 2016, 208, 0.07),
 ('AUXC', 'Forced', 2016, 206, 0.08),
 ('MELK', 'Forced', 2017, 177, 2.28),
 ('TRMOS', 'Forced', 2017, 172, 0.42),
 ('MELK', 'Forced', 2016, 157, 0.83),
 ('PUG', 'Forced', 2017, 135, 0.25),
 ('AUXC', 'Forced', 2017, 120, 0.02),
 ('MELK', 'Scheduled (Planned)', 2016, 85, 4.61),
 ('PJRH', 'Forced', 2016, 81, 1.22),
 ('KORL', 'Forced', 2017, 76, 1.21),
 ('PJRH', 'Forced', 2017, 72, 0.84),
 ('MELK', 'Scheduled (Planned)', 2017, 70, 6.89),
 ('PMC', 'Forced', 2016, 69, 0.49),
 ('TRMOS', 'Forced', 2016, 65, 0.19),
 ('KORL', 'Forced', 2016, 53, 0.38),
 ('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89),
 ('COLLGAR', 'Forced', 2017, 45, 1.38),
 ('GW', 'Scheduled (Planned)', 2016, 45, 4.43),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45),
 ('AURICON', 'Consequential', 2017, 42, 0.21),
 ('AURICON', 'Consequential', 2016, 41, 0.13),
 ('PMC', 'Forced', 2017, 40, 0.04),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2017, 39, 0.24),
 ('PJRH', 'Scheduled (Planned)', 2016, 38, 2.37),
 ('ENRG', 'Scheduled (Planned)', 2017, 37, 4.96),
 ('PJRH', 'Scheduled (Planned)', 2017, 35, 2.61),
 ('TSLA_MGT', 'Consequential', 2016, 30, 0.44),
 ('COLLGAR', 'Forced', 2016, 29, 1.11),
 ('ENRG', 'Scheduled (Planned)', 2016, 29, 4.85),
 ('TSLA_MGT', 'Scheduled (Planned)', 2017, 28, 0.99),
 ('PMC', 'Scheduled (Planned)', 2016, 27, 1.9),
 ('GW', 'Scheduled (Planned)', 2017, 26, 2.65),
 ('PUG', 'Forced', 2016, 24, 0.92),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2016, 24, 0.71),
 ('TSLA_MGT', 'Consequential', 2017, 23, 0.34),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2016, 23, 0.18),
 ('TSLA_MGT', 'Scheduled (Planned)', 2016, 23, 1.97),
 ('ENRG', 'Forced', 2016, 21, 2.24),
 ('GW', 'Consequential', 2016, 20, 0.18),
 ('GW', 'Opportunistic Maintenance (Planned)', 2016, 20, 0.31),
 ('KORL', 'Scheduled (Planned)', 2016, 20, 6.96),
 ('STHRNCRS', 'Forced', 2017, 18, 0.26),
 ('MUND', 'Scheduled (Planned)', 2016, 18, 3.53),
 ('EUCT', 'Consequential', 2016, 17, 0.41),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2017, 16, 0.65),
 ('PUG', 'Scheduled (Planned)', 2016, 16, 1.47),
 ('KORL', 'Scheduled (Planned)', 2017, 16, 3.38),
 ('ENRG', 'Consequential', 2016, 15, 0.57),
 ('MUND', 'Forced', 2017, 15, 0.19),
 ('EUCT', 'Consequential', 2017, 14, 0.32),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2016, 14, 0.22),
 ('STHRNCRS', 'Scheduled (Planned)', 2017, 14, 0.68),
 ('STHRNCRS', 'Forced', 2016, 13, 0.33),
 ('GW', 'Opportunistic Maintenance (Planned)', 2017, 13, 0.28),
 ('STHRNCRS', 'Scheduled (Planned)', 2016, 13, 0.62),
 ('COLLGAR', 'Consequential', 2016, 12, 0.6),
 ('DNHR', 'Consequential', 2017, 12, 0.24),
 ('MCG', 'Forced', 2017, 12, 0.28),
 ('COLLGAR', 'Scheduled (Planned)', 2016, 12, 4.28),
 ('PMC', 'Scheduled (Planned)', 2017, 12, 1.7),
 ('DNHR', 'Consequential', 2016, 11, 0.28),
 ('EUCT', 'Forced', 2016, 11, 5.9),
 ('PUG', 'Scheduled (Planned)', 2017, 11, 2.25),
 ('PMC', 'Consequential', 2016, 10, 0.28),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2017, 10, 0.24),
 ('STHRNCRS', 'Consequential', 2016, 9, 0.22),
 ('MUND', 'Opportunistic Maintenance (Planned)', 2017, 9, 0.21),
 ('COLLGAR', 'Scheduled (Planned)', 2017, 9, 6.36),
 ('PMC', 'Consequential', 2017, 8, 3.52),
 ('WGUTD', 'Forced', 2017, 8, 3.44),
 ('MUND', 'Opportunistic Maintenance (Planned)', 2016, 8, 0.15),
 ('MELK', 'Consequential', 2016, 7, 0.76),
 ('ENRG', 'Consequential', 2017, 7, 0.27),
 ('ENRG', 'Forced', 2017, 7, 0.26),
 ('PUG', 'Opportunistic Maintenance (Planned)', 2016, 7, 0.21),
 ('MUND', 'Scheduled (Planned)', 2017, 7, 1.7),
 ('WGUTD', 'Consequential', 2016, 6, 1.99),
 ('KORL', 'Consequential', 2017, 6, 2.24),
 ('COLLGAR', 'Consequential', 2017, 5, 0.23),
 ('COLLGAR', 'Opportunistic Maintenance (Planned)', 2017, 5, 0.33),
 ('TRMOS', 'Scheduled (Planned)', 2016, 5, 1.42),
 ('GW', 'Consequential', 2017, 4, 0.24),
 (

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[('AURICON', 'Forced', 2017, 490, 0.07),
 ('GW', 'Forced', 2016, 317, 0.38),
 ('GW', 'Forced', 2017, 227, 1.06),
 ('AURICON', 'Forced', 2016, 208, 0.07),
 ('AUXC', 'Forced', 2016, 206, 0.08)]

Now we're getting somewhere...!
We've identified participants who are having many outages, as well as participants who have been offline for the longest durations.

Armed with this information, it's important we're able to classify our participants accordingly based on reliability metrics of uptime.

We classify a participant based off the following criteria:
<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day)</li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours</li> 
</b>

<h3 style="color:#D4AF37"> Question Four </h3>

<b> Using the above criteria for context, write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> that is based off their Average Outage Duration Time. Please note that this is for all valid (i.e. `Where status = approved`) outage types (Forced, Consequential, Scheduled, Opportunistic) for <u>all</u> participant codes from 2016 to 2017. Order the results using `Average Duration Time In Days` in descending order. 

<b>⚠️Hint: Think about the CASE Statement and how you might use this to help you with your classification! This is a more challenging question so you'll need to think through this step by step. You might also find `CTEs` or `Sub Queries` helpful for you.</b>


<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [7]:
%%sql
WITH CTE1 AS (
SELECT
    Participant_Code,
    Outage_Reason,
    Year,
    COUNT(*) AS Total_Number_Outage_Events,
    ROUND(AVG(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))),2) AS Average_Outage_Duration_In_Days

FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved'
GROUP BY
    Participant_Code, Outage_Reason, Year
ORDER BY
    Total_Number_Outage_Events DESC)

SELECT *,
    CASE
        WHEN Average_Outage_Duration_In_Days > 1 THEN 'High Risk'
        WHEN Average_Outage_Duration_In_Days BETWEEN 0.5 AND 1 THEN 'Medium Risk'
        WHEN Average_Outage_Duration_In_Days < 0.5 THEN 'Low Risk'
    END AS Risk_Classification
FROM
    CTE1


 * sqlite:///AEMR.db
Done.


[('AURICON', 'Forced', 2017, 490, 0.07, 'Low Risk'),
 ('GW', 'Forced', 2016, 317, 0.38, 'Low Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk'),
 ('AURICON', 'Forced', 2016, 208, 0.07, 'Low Risk'),
 ('AUXC', 'Forced', 2016, 206, 0.08, 'Low Risk'),
 ('MELK', 'Forced', 2017, 177, 2.28, 'High Risk'),
 ('TRMOS', 'Forced', 2017, 172, 0.42, 'Low Risk'),
 ('MELK', 'Forced', 2016, 157, 0.83, 'Medium Risk'),
 ('PUG', 'Forced', 2017, 135, 0.25, 'Low Risk'),
 ('AUXC', 'Forced', 2017, 120, 0.02, 'Low Risk'),
 ('MELK', 'Scheduled (Planned)', 2016, 85, 4.61, 'High Risk'),
 ('PJRH', 'Forced', 2016, 81, 1.22, 'High Risk'),
 ('KORL', 'Forced', 2017, 76, 1.21, 'High Risk'),
 ('PJRH', 'Forced', 2017, 72, 0.84, 'Medium Risk'),
 ('MELK', 'Scheduled (Planned)', 2017, 70, 6.89, 'High Risk'),
 ('PMC', 'Forced', 2016, 69, 0.49, 'Low Risk'),
 ('TRMOS', 'Forced', 2016, 65, 0.19, 'Low Risk'),
 ('KORL', 'Forced', 2016, 53, 0.38, 'Low Risk'),
 ('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89, 'High Risk'),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45, 'High Risk'),
 ('COLLGAR', 'Forced', 2017, 45, 1.38, 'High Risk'),
 ('GW', 'Scheduled (Planned)', 2016, 45, 4.43, 'High Risk'),
 ('AURICON', 'Consequential', 2017, 42, 0.21, 'Low Risk'),
 ('AURICON', 'Consequential', 2016, 41, 0.13, 'Low Risk'),
 ('PMC', 'Forced', 2017, 40, 0.04, 'Low Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2017, 39, 0.24, 'Low Risk'),
 ('PJRH', 'Scheduled (Planned)', 2016, 38, 2.37, 'High Risk'),
 ('ENRG', 'Scheduled (Planned)', 2017, 37, 4.96, 'High Risk'),
 ('PJRH', 'Scheduled (Planned)', 2017, 35, 2.61, 'High Risk'),
 ('TSLA_MGT', 'Consequential', 2016, 30, 0.44, 'Low Risk'),
 ('COLLGAR', 'Forced', 2016, 29, 1.11, 'High Risk'),
 ('ENRG', 'Scheduled (Planned)', 2016, 29, 4.85, 'High Risk'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2017, 28, 0.99, 'Medium Risk'),
 ('PMC', 'Scheduled (Planned)', 2016, 27, 1.9, 'High Risk'),
 ('GW', 'Scheduled (Planned)', 2017, 26, 2.65, 'High Risk'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2016, 24, 0.71, 'Medium Risk'),
 ('PUG', 'Forced', 2016, 24, 0.92, 'Medium Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2016, 23, 0.18, 'Low Risk'),
 ('TSLA_MGT', 'Consequential', 2017, 23, 0.34, 'Low Risk'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2016, 23, 1.97, 'High Risk'),
 ('ENRG', 'Forced', 2016, 21, 2.24, 'High Risk'),
 ('GW', 'Consequential', 2016, 20, 0.18, 'Low Risk'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2016, 20, 0.31, 'Low Risk'),
 ('KORL', 'Scheduled (Planned)', 2016, 20, 6.96, 'High Risk'),
 ('MUND', 'Scheduled (Planned)', 2016, 18, 3.53, 'High Risk'),
 ('STHRNCRS', 'Forced', 2017, 18, 0.26, 'Low Risk'),
 ('EUCT', 'Consequential', 2016, 17, 0.41, 'Low Risk'),
 ('KORL', 'Scheduled (Planned)', 2017, 16, 3.38, 'High Risk'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2017, 16, 0.65, 'Medium Risk'),
 ('PUG', 'Scheduled (Planned)', 2016, 16, 1.47, 'High Risk'),
 ('ENRG', 'Consequential', 2016, 15, 0.57, 'Medium Risk'),
 ('MUND', 'Forced', 2017, 15, 0.19, 'Low Risk'),
 ('EUCT', 'Consequential', 2017, 14, 0.32, 'Low Risk'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2016, 14, 0.22, 'Low Risk'),
 ('STHRNCRS', 'Scheduled (Planned)', 2017, 14, 0.68, 'Medium Risk'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2017, 13, 0.28, 'Low Risk'),
 ('STHRNCRS', 'Forced', 2016, 13, 0.33, 'Low Risk'),
 ('STHRNCRS', 'Scheduled (Planned)', 2016, 13, 0.62, 'Medium Risk'),
 ('COLLGAR', 'Consequential', 2016, 12, 0.6, 'Medium Risk'),
 ('COLLGAR', 'Scheduled (Planned)', 2016, 12, 4.28, 'High Risk'),
 ('DNHR', 'Consequential', 2017, 12, 0.24, 'Low Risk'),
 ('MCG', 'Forced', 2017, 12, 0.28, 'Low Risk'),
 ('PMC', 'Scheduled (Planned)', 2017, 12, 1.7, 'High Risk'),
 ('DNHR', 'Consequential', 2016, 11, 0.28, 'Low Risk'),
 ('EUCT', 'Forced', 2016, 11, 5.9, 'High Risk'),
 ('PUG', 'Scheduled (Planned)', 2017, 11, 2.25, 'High Risk'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2017, 10, 0.24, 'Low Risk'),
 ('PMC', 'Conseque

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[('AURICON', 'Forced', 2017, 490, 0.07, 'Low Risk'),
 ('GW', 'Forced', 2016, 317, 0.38, 'Low Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk')]

Now that we've classified our participants as either `High Risk`, `Medium Risk` or `Low Risk`, we want to dig a little deeper.

Does it make sense that `Consequential`, `Opportunistic` or `Planned` aren't considered regarding the Risk Category?

Perhaps we should refine our category accordingly by ensuring we focus our Risk Category on labelling only `Forced` Outages as being a Risk. After all, Forced Outages are the unplanned outages that risk the security of the electricity grid.

Let's add two additional criteria to our classification considering `Total Number of Outage Events` and `Outage Type`.

We've summarised these below:

<b>
<li> High Risk - On average, the participant is unavailable for > 24 Hours (1 Day) OR the Total Number of Outage Events > 20 </li>
<li> Medium Risk - On average, the participant is unavailable between 12 and 24 Hours OR the Total Number of Outage Events is Between 10 and 20 </li>
<li> Low Risk - On average, the participant is unavailable for less than 12 Hours OR the Total Number of Outage Events < 10 </li> 
<li> If Outage Type is not forced, then N/A
</b>


<h3 style="color:#D4AF37"> Question Five </h3>

<b> Just as you did in Question Four, Using the above criteria for context, write a SQL Statement that <u> classifies each participant code as either `High Risk`, `Medium Risk` or `Low Risk` in a column called `Risk_Classification`</u> using the new classification criteria. Order the results using `Average Duration Time In Days` in descending order. 

<b>⚠️Hint: Think about the CASE Statement and how you might use this to help you with your classification! </b>


<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [8]:
%%sql
WITH CTE1 AS (
    SELECT
        Participant_Code,
        Outage_Reason,
        Year,
        COUNT(*) AS Total_Number_Outage_Events,
        ROUND(AVG(ABS(JULIANDAY(End_Time) - JULIANDAY(Start_Time))), 2) AS Average_Outage_Duration_In_Days
    FROM
        AEMR_Outage_Table
    WHERE
        Status = 'Approved'
    GROUP BY
        Participant_Code, Outage_Reason, Year
    ORDER BY
        Total_Number_Outage_Events DESC
)

SELECT *,
    CASE
        WHEN (Average_Outage_Duration_In_Days > 1 OR Total_Number_Outage_Events > 20) AND Outage_Reason = 'Forced' THEN 'High Risk'
        WHEN (Average_Outage_Duration_In_Days BETWEEN 0.5 AND 1 OR Total_Number_Outage_Events BETWEEN 10 AND 20) AND Outage_Reason = 'Forced' THEN 'Medium Risk'
        WHEN (Average_Outage_Duration_In_Days < 0.5 OR Total_Number_Outage_Events < 10) AND Outage_Reason = 'Forced' THEN 'Low Risk'
        ELSE 'N/A'
    END AS Risk_Classification
FROM
    CTE1;


 * sqlite:///AEMR.db
Done.


[('AURICON', 'Forced', 2017, 490, 0.07, 'High Risk'),
 ('GW', 'Forced', 2016, 317, 0.38, 'High Risk'),
 ('GW', 'Forced', 2017, 227, 1.06, 'High Risk'),
 ('AURICON', 'Forced', 2016, 208, 0.07, 'High Risk'),
 ('AUXC', 'Forced', 2016, 206, 0.08, 'High Risk'),
 ('MELK', 'Forced', 2017, 177, 2.28, 'High Risk'),
 ('TRMOS', 'Forced', 2017, 172, 0.42, 'High Risk'),
 ('MELK', 'Forced', 2016, 157, 0.83, 'High Risk'),
 ('PUG', 'Forced', 2017, 135, 0.25, 'High Risk'),
 ('AUXC', 'Forced', 2017, 120, 0.02, 'High Risk'),
 ('MELK', 'Scheduled (Planned)', 2016, 85, 4.61, 'N/A'),
 ('PJRH', 'Forced', 2016, 81, 1.22, 'High Risk'),
 ('KORL', 'Forced', 2017, 76, 1.21, 'High Risk'),
 ('PJRH', 'Forced', 2017, 72, 0.84, 'High Risk'),
 ('MELK', 'Scheduled (Planned)', 2017, 70, 6.89, 'N/A'),
 ('PMC', 'Forced', 2016, 69, 0.49, 'High Risk'),
 ('TRMOS', 'Forced', 2016, 65, 0.19, 'High Risk'),
 ('KORL', 'Forced', 2016, 53, 0.38, 'High Risk'),
 ('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89, 'N/A'),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45, 'N/A'),
 ('COLLGAR', 'Forced', 2017, 45, 1.38, 'High Risk'),
 ('GW', 'Scheduled (Planned)', 2016, 45, 4.43, 'N/A'),
 ('AURICON', 'Consequential', 2017, 42, 0.21, 'N/A'),
 ('AURICON', 'Consequential', 2016, 41, 0.13, 'N/A'),
 ('PMC', 'Forced', 2017, 40, 0.04, 'High Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2017, 39, 0.24, 'N/A'),
 ('PJRH', 'Scheduled (Planned)', 2016, 38, 2.37, 'N/A'),
 ('ENRG', 'Scheduled (Planned)', 2017, 37, 4.96, 'N/A'),
 ('PJRH', 'Scheduled (Planned)', 2017, 35, 2.61, 'N/A'),
 ('TSLA_MGT', 'Consequential', 2016, 30, 0.44, 'N/A'),
 ('COLLGAR', 'Forced', 2016, 29, 1.11, 'High Risk'),
 ('ENRG', 'Scheduled (Planned)', 2016, 29, 4.85, 'N/A'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2017, 28, 0.99, 'N/A'),
 ('PMC', 'Scheduled (Planned)', 2016, 27, 1.9, 'N/A'),
 ('GW', 'Scheduled (Planned)', 2017, 26, 2.65, 'N/A'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2016, 24, 0.71, 'N/A'),
 ('PUG', 'Forced', 2016, 24, 0.92, 'High Risk'),
 ('PJRH', 'Opportunistic Maintenance (Planned)', 2016, 23, 0.18, 'N/A'),
 ('TSLA_MGT', 'Consequential', 2017, 23, 0.34, 'N/A'),
 ('TSLA_MGT', 'Scheduled (Planned)', 2016, 23, 1.97, 'N/A'),
 ('ENRG', 'Forced', 2016, 21, 2.24, 'High Risk'),
 ('GW', 'Consequential', 2016, 20, 0.18, 'N/A'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2016, 20, 0.31, 'N/A'),
 ('KORL', 'Scheduled (Planned)', 2016, 20, 6.96, 'N/A'),
 ('MUND', 'Scheduled (Planned)', 2016, 18, 3.53, 'N/A'),
 ('STHRNCRS', 'Forced', 2017, 18, 0.26, 'Medium Risk'),
 ('EUCT', 'Consequential', 2016, 17, 0.41, 'N/A'),
 ('KORL', 'Scheduled (Planned)', 2017, 16, 3.38, 'N/A'),
 ('MELK', 'Opportunistic Maintenance (Planned)', 2017, 16, 0.65, 'N/A'),
 ('PUG', 'Scheduled (Planned)', 2016, 16, 1.47, 'N/A'),
 ('ENRG', 'Consequential', 2016, 15, 0.57, 'N/A'),
 ('MUND', 'Forced', 2017, 15, 0.19, 'Medium Risk'),
 ('EUCT', 'Consequential', 2017, 14, 0.32, 'N/A'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2016, 14, 0.22, 'N/A'),
 ('STHRNCRS', 'Scheduled (Planned)', 2017, 14, 0.68, 'N/A'),
 ('GW', 'Opportunistic Maintenance (Planned)', 2017, 13, 0.28, 'N/A'),
 ('STHRNCRS', 'Forced', 2016, 13, 0.33, 'Medium Risk'),
 ('STHRNCRS', 'Scheduled (Planned)', 2016, 13, 0.62, 'N/A'),
 ('COLLGAR', 'Consequential', 2016, 12, 0.6, 'N/A'),
 ('COLLGAR', 'Scheduled (Planned)', 2016, 12, 4.28, 'N/A'),
 ('DNHR', 'Consequential', 2017, 12, 0.24, 'N/A'),
 ('MCG', 'Forced', 2017, 12, 0.28, 'Medium Risk'),
 ('PMC', 'Scheduled (Planned)', 2017, 12, 1.7, 'N/A'),
 ('DNHR', 'Consequential', 2016, 11, 0.28, 'N/A'),
 ('EUCT', 'Forced', 2016, 11, 5.9, 'High Risk'),
 ('PUG', 'Scheduled (Planned)', 2017, 11, 2.25, 'N/A'),
 ('KORL', 'Opportunistic Maintenance (Planned)', 2017, 10, 0.24, 'N/A'),
 ('PMC', 'Consequential', 2016, 10, 0.28, 'N/A'),
 ('COLLGAR', 'Scheduled (Planned)', 2017, 9, 6.36, 'N/A'),
 ('MUND', 'Opportunistic Maintenance (Planned)', 2017, 9, 0.21, 'N/A'),
 ('STHRNCRS', 'Consequential', 2016, 9, 0.22, 'N/A'),
 ('MUND', '

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>

 * sqlite:///AEMR.db
Done.


[('AURICON', 'Scheduled (Planned)', 2016, 46, 1.89, 'N/A'),
 ('AURICON', 'Scheduled (Planned)', 2017, 45, 1.45, 'N/A'),
 ('AURICON', 'Opportunistic Maintenance (Planned)', 2016, 3, 0.33, 'N/A')]

<h3 style="color:#D4AF37"> ⚡ Part II. Energy Losses & Market Reliability ⚡ </h3>

When an energy provider provides energy to the market, they are making a commitment to the market and saying; “We will supply X amount of energy to the market under a contractual obligation.” However, in a situation where the outages are Forced, the energy provider intended to provide energy but are unable to provide energy and are forced offline. <b style="color:Maroon">If many energy providers are forced offline at the same time it could cause an energy security risk that AEMR needs to mitigate. </b>

To ensure this doesn’t happen, the AEMR is interested in exploring the following questions:

<li> Of the outage types in 2016 and 2017, what percent were Forced Outage(s)?
<li> What was the average duration for a forced outage during both 2016 and 2017? Have we seen an increase in the average duration of forced outages?
<li> Which energy providers tended to have the largest number of forced outages?
    
<p>

<b> We'll examine this in the questions below. </b>
    
<img src = "https://media.istockphoto.com/id/1281821795/photo/market-stock-graph-and-information-with-city-light-and-electricity-and-energy-facility-banner.jpg?s=612x612&w=0&k=20&c=RSN5LqeMW28HW10aA190_DWR5YJ5tG2wixHFPBV3uZE=">

<h3 style="color:#D4AF37"> Question Six </h3>

<b> Write a SQL Statement to calculate the proportion of Forced Outages that have occurred over the 2016 - 2017 Period.
Do we observe any particular increases regarding any Outage Types over this period? </b>

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [9]:
%%sql
SELECT
    COUNT(*) AS Total_Number_Outage_Events,
    SUM(CASE WHEN Outage_Reason = 'Forced' THEN 1 ELSE 0 END) as Total_Number_Forced_Outage_Events,
    ROUND(SUM((CASE WHEN Outage_Reason = 'Forced' THEN 1 ELSE 0 END) * 1.0)/COUNT(*)*100,2) as Pct_Outage_Forced,
    Year
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved'
GROUP BY
    Year

 * sqlite:///AEMR.db
Done.


[(1931, 1264, 65.46, 2016), (2171, 1622, 74.71, 2017)]

The analysis indicates a rise in forced outages from approximately 65.46% in 2016 to 74.71% in 2017, reflecting an increase in forced disruptions within the electricity grid during this period.

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(1931, 1264, 65.46), (2171, 1622, 74.71)]

Great. It's clear to see now that `Forced Outages` are problematic for us. Not only are they the only outage type that generates financial losses as the Outage is unplanned, it seems there is a number of Energy Participants who have been having a significantly high number of Outages.

Now what can we do about this? 

Let's break our analysis down into Macro and Micro Analysis.
The total gives us the Overall Duration a participant is offline / has lost energy, however, it doesn't tell us how *frequently* this occurs. In other words, if we have one or two very big outages, it might contribute to very large totals.

However, perhaps an <b> average </b> can help us identify how big these Outages might really be, spread across the year!

Let's take a look.

<h3 style="color:#D4AF37"> Question Seven </h3>

Write a SQL Statement to calculate the `Total Number of Outages`, `Total Duration In Days`and `Total Energy Lost` of all valid `Outages` for each `participant code` and `facility_code`, sorted by `Total Energy Lost` in descending order and Ordered by the YEAR Category. 
    

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [10]:
%%sql
SELECT
    COUNT(*) AS Total_Number_Outage,
    ROUND(SUM(ABS((JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Total_Duration_In_Days,
    ROUND(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
    Outage_Reason,
    Participant_Code,
    Facility_Code,
    Year
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved'
GROUP BY
    Outage_Reason, Participant_Code, Facility_Code, Year
ORDER BY
    Total_Energy_Lost DESC, Year DESC

 * sqlite:///AEMR.db
Done.


[(490, 33.65, 21639.55, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (227, 240.69, 19326.56, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (317, 120.6, 15751.38, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (157, 129.6, 13771.07, 'Forced', 'MELK', 'MELK_G7', 2016),
 (208, 15.06, 10696.28, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (177, 404.15, 10285.4, 'Forced', 'MELK', 'MELK_G7', 2017),
 (85, 392.25, 9668.79, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2016),
 (69, 34.06, 9093.09, 'Forced', 'PMC', 'PMC_AG', 2016),
 (70, 482.58, 7499.28, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2017),
 (46, 87.02, 6964.8, 'Scheduled (Planned)', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (45, 199.4, 6450.0, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (45, 65.4, 5941.25, 'Scheduled (Planned)', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (81, 98.79, 5881.52, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (40, 1.56, 5648.44, 'Forced', 'PMC', 'PMC_AG', 2017),
 (172, 71.9, 5016.67, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (72, 60.13, 4839.28, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (27, 51.4, 4839.0, 'Scheduled (Planned)', 'PMC', 'PMC_AG', 2016),
 (76, 91.79, 4679.68, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (29, 32.33, 4320.86, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (135, 33.4, 4112.1, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (53, 20.0, 4040.32, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (41, 5.31, 3925.55, 'Consequential', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (26, 68.9, 3812.42, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (39, 9.17, 3100.95, 'Opportunistic Maintenance (Planned)', 'PJRH', 'PJRH_GT11', 2017),
 (20, 6.21, 2951.0, 'Opportunistic Maintenance (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (24, 17.0, 2877.04, 'Opportunistic Maintenance (Planned)', 'MELK', 'MELK_G7', 2016),
 (45, 62.1, 2787.06, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (206, 16.04, 2734.14, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (42, 8.88, 2553.24, 'Consequential', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (38, 89.9, 2445.0, 'Scheduled (Planned)', 'PJRH', 'PJRH_GT11', 2016),
 (23, 4.21, 2178.95, 'Opportunistic Maintenance (Planned)', 'PJRH', 'PJRH_GT11', 2016),
 (12, 51.38, 2139.87, 'Scheduled (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (35, 91.35, 2110.01, 'Scheduled (Planned)', 'PJRH', 'PJRH_GT11', 2017),
 (120, 2.1, 1768.76, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (20, 139.25, 1685.6, 'Scheduled (Planned)', 'KORL', 'KORL_GT3', 2016),
 (8, 28.15, 1672.66, 'Consequential', 'PMC', 'PMC_AG', 2017),
 (12, 20.35, 1639.2, 'Scheduled (Planned)', 'PMC', 'PMC_AG', 2017),
 (9, 57.27, 1632.78, 'Scheduled (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (7, 5.35, 1524.82, 'Consequential', 'MELK', 'MELK_G7', 2016),
 (13, 3.67, 1423.53, 'Opportunistic Maintenance (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (12, 7.15, 1374.0, 'Consequential', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (16, 10.44, 1339.7, 'Opportunistic Maintenance (Planned)', 'MELK', 'MELK_G7', 2017),
 (16, 23.56, 1334.0, 'Scheduled (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (16, 54.1, 1326.6, 'Scheduled (Planned)', 'KORL', 'KORL_GT3', 2017),
 (65, 12.63, 1232.43, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (21, 47.04, 1182.8, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (14, 3.04, 1172.05, 'Opportunistic Maintenance (Planned)', 'KORL', 'KORL_GT3', 2016),
 (11, 24.73, 1160.0, 'Scheduled (Planned)', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (5, 1.17, 926.0, 'Consequential', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (10, 2.42, 842.8, 'Opportunistic Maintenance (Planned)', 'KORL', 'KORL_GT3', 2017),
 (20, 3.6, 832.72, 'Consequential', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (24, 22.17, 815.47, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (5, 1.65, 763.96, 'Opportunistic Maintenance (Planned)', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (28, 27.75, 678.4, 'Scheduled (Planned)', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (18, 63.46, 664.0, 'Scheduled (Planned)', 'MUND', 'MUNDARING_GT1', 2016),
 (10, 2.81, 643.0, 'Consequential

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(70, 482.58, 7499.28, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2017),
 (177, 404.15, 10285.4, 'Forced', 'MELK', 'MELK_G7', 2017),
 (85, 392.25, 9668.79, 'Scheduled (Planned)', 'MELK', 'MELK_G7', 2016),
 (227, 240.69, 19326.56, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (45, 199.4, 6450.0, 'Scheduled (Planned)', 'GW', 'BW1_GREENWATERS_G2', 2016)]

<h3 style="color:#D4AF37"> Question Eight </h3>

<b> Write a SQL Statement to calculate the `Average Duration In Days`and `Average Energy Lost` of all valid `FORCED OUTAGES` for each `participant code` and `facility_code` sorted by `Average Energy Lost` in descending order and Ordered by the YEAR Category. 


<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [11]:
%%sql
SELECT
    ROUND(AVG(ABS((JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Avg_Duration_In_Days,
    ROUND(AVG(Energy_Lost_MW),2) as Avg_Energy_Lost,
    Outage_Reason,
    Participant_Code,
    Facility_Code,
    Year
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved' AND Outage_Reason = 'Forced'
GROUP BY
    Year, Outage_Reason, Participant_Code, Facility_Code
ORDER BY
    Avg_Duration_In_Days DESC, Year DESC


 * sqlite:///AEMR.db
Done.


[(5.9, 5.89, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (3.44, 27.66, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (2.28, 58.11, 'Forced', 'MELK', 'MELK_G7', 2017),
 (2.24, 56.32, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (1.38, 61.93, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (1.22, 72.61, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (1.21, 61.57, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (1.11, 149.0, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (1.06, 85.14, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (0.92, 33.98, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (0.84, 67.21, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (0.83, 87.71, 'Forced', 'MELK', 'MELK_G7', 2016),
 (0.79, 55.0, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (0.49, 131.78, 'Forced', 'PMC', 'PMC_AG', 2016),
 (0.48, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (0.42, 29.17, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (0.4, 1.44, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016),
 (0.38, 49.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (0.38, 76.23, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (0.37, 36.8, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (0.33, 23.0, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (0.31, 42.48, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (0.28, 46.94, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (0.26, 27.41, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (0.26, 16.26, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (0.25, 30.46, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (0.25, 80.0, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (0.19, 26.57, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (0.19, 18.96, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (0.08, 13.27, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (0.07, 44.16, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (0.07, 51.42, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (0.04, 141.21, 'Forced', 'PMC', 'PMC_AG', 2017),
 (0.03, 21.6, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (0.02, 14.74, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (0.02, 27.0, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016)]

In [12]:
%%sql
SELECT
    ROUND(AVG(ABS((JULIANDAY(End_Time) - JULIANDAY(Start_Time)))),2) as Avg_Duration_In_Days,
    Outage_Reason,
    Year
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved' AND Outage_Reason = 'Forced'
GROUP BY
    Outage_Reason, Year

 * sqlite:///AEMR.db
Done.


[(0.49, 'Forced', 2016), (0.64, 'Forced', 2017)]

Average duration of Forced Outage in 2016 is 0.49 and in 2017 it is increased to 0.64.

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(5.9, 5.89, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (3.44, 27.66, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (2.28, 58.11, 'Forced', 'MELK', 'MELK_G7', 2017)]

<h3 style="color:#D4AF37"> Question Nine </h3>

<b> Write a SQL Statement to calculate the `Average Energy Lost` and `Total Energy Lost` for each `Facility Code` and `Participant Code` across both the 2016 and 2017 periods when the `Outage_Reason` is set to Forced. Upon completion of this, calculate the <u> percentage </u> of energy lost due to forced outages for each `Facility_Code`. Please ORDER the query by `Total Energy Lost` from 2016 to 2017.
    
From your analysis, which participants have contributed the most to the Energy Lost due to Forced Outages?


<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [13]:
%%sql
SELECT
    ROUND(AVG(Energy_Lost_MW),2) as Avg_Energy_Lost,
    ROUND(SUM(Energy_Lost_MW),2) as Total_Energy_Lost,
    ROUND(SUM(Energy_Lost_MW) / (SELECT SUM(Energy_Lost_MW) FROM AEMR_Outage_Table WHERE Status = 'Approved' AND Outage_Reason = 'Forced')*100,2) as Pct_Energy_Lost,
    Outage_Reason,
    Participant_Code,
    Facility_Code,
    Year
FROM
    AEMR_Outage_Table
WHERE
    Status = 'Approved' AND Outage_Reason = 'Forced'
GROUP BY
    Year, Outage_Reason, Participant_Code, Facility_Code
ORDER BY
    Total_Energy_Lost DESC, Year DESC

 * sqlite:///AEMR.db
Done.


[(44.16, 21639.55, 14.21, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (85.14, 19326.56, 12.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (49.69, 15751.38, 10.34, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016),
 (87.71, 13771.07, 9.04, 'Forced', 'MELK', 'MELK_G7', 2016),
 (51.42, 10696.28, 7.02, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2016),
 (58.11, 10285.4, 6.75, 'Forced', 'MELK', 'MELK_G7', 2017),
 (131.78, 9093.09, 5.97, 'Forced', 'PMC', 'PMC_AG', 2016),
 (72.61, 5881.52, 3.86, 'Forced', 'PJRH', 'PJRH_GT11', 2016),
 (141.21, 5648.44, 3.71, 'Forced', 'PMC', 'PMC_AG', 2017),
 (29.17, 5016.67, 3.29, 'Forced', 'TRMOS', 'TIWEST_COG1', 2017),
 (67.21, 4839.28, 3.18, 'Forced', 'PJRH', 'PJRH_GT11', 2017),
 (61.57, 4679.68, 3.07, 'Forced', 'KORL', 'KORL_GT3', 2017),
 (149.0, 4320.86, 2.84, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2016),
 (30.46, 4112.1, 2.7, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2017),
 (76.23, 4040.32, 2.65, 'Forced', 'KORL', 'KORL_GT3', 2016),
 (61.93, 2787.06, 1.83, 'Forced', 'COLLGAR', 'COLLGAR_WF1', 2017),
 (13.27, 2734.14, 1.8, 'Forced', 'AUXC', 'AUXC_WGP', 2016),
 (14.74, 1768.76, 1.16, 'Forced', 'AUXC', 'AUXC_WGP', 2017),
 (18.96, 1232.43, 0.81, 'Forced', 'TRMOS', 'TIWEST_COG1', 2016),
 (56.32, 1182.8, 0.78, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2016),
 (33.98, 815.47, 0.54, 'Forced', 'PUG', 'PERTHENERGY_KORL_GT1', 2016),
 (46.94, 563.33, 0.37, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2017),
 (26.57, 398.58, 0.26, 'Forced', 'MUND', 'MUNDARING_GT1', 2017),
 (23.0, 299.0, 0.2, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2016),
 (16.26, 292.7, 0.19, 'Forced', 'STHRNCRS', 'STHRNCRS_EG', 2017),
 (27.66, 221.29, 0.15, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2017),
 (27.41, 191.86, 0.13, 'Forced', 'ENRG', 'ENRG_KALGOORLIE_GT3', 2017),
 (42.48, 169.9, 0.11, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2017),
 (80.0, 160.0, 0.11, 'Forced', 'TSLA_MGT', 'TESLA_PICTON_G1', 2016),
 (36.8, 147.2, 0.1, 'Forced', 'MUND', 'MUNDARING_GT1', 2016),
 (21.6, 64.8, 0.04, 'Forced', 'EUCT', 'GRASMERE_WF1', 2017),
 (5.89, 64.8, 0.04, 'Forced', 'EUCT', 'GRASMERE_WF1', 2016),
 (55.0, 55.0, 0.04, 'Forced', 'MCG', 'MWF_MUMBIDA_WF1', 2016),
 (27.0, 54.0, 0.04, 'Forced', 'WGUTD', 'WEST_KALGOORLIE_GT2', 2016),
 (1.44, 1.44, 0.0, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2017),
 (1.44, 1.44, 0.0, 'Forced', 'DNHR', 'DNHR_DENMARK_WF1', 2016)]

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[(44.16, 21639.55, 14.21, 'Forced', 'AURICON', 'AURICON_PNJ_U1', 2017),
 (85.14, 19326.56, 12.69, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2017),
 (49.69, 15751.38, 10.34, 'Forced', 'GW', 'BW1_GREENWATERS_G2', 2016)]

<h3 style="color:#D4AF37"> Question Ten </h3>

<b>Having identified the top 3 participants by Total Energy Loss being `GW`, `MELK` and `Auricon`; Write a SQL Statement calculating the `Total_Energy_Lost` each of these three `Participant_Codes` and the `Facility_Code`. Additionally, identify the `Description_Of_Outage` associated with the highest `Total_Energy_Lost` for each of the `Participant_Codes` and `Facility_Code` for each of the three participants. 
    
<u>Lastly, calculate the percentage of Energy Loss, attributed to these reasons!</u> </b>

<b> ⚠️ Hint: As this is the final question, this is a bit of a <b> challenge question </b> which will involve some SQL functions you're not familiar with just yet. In the workplace, you're going to have to grow familiar with googling and searching for functions that you may have not learned or be familiar with. In this question, to identify the TOP `Description_Of_Outage` reason for each Participant, you're going to need to use `PARTITION BY`. You can read all about the approach you can take in this example <a href = "https://learnsql.com/cookbook/how-to-rank-rows-within-a-partition-in-sql/#:~:text=To%20partition%20rows%20and%20rank,rank%20rows%20within%20a%20partition."> here </a>. Good luck! 

<h4 style="color:Teal"> Please write your SQL in the code window below </h4>

In [14]:
%%sql
SELECT
    Participant_Code,
    Facility_Code,
    Description_Of_Outage,
    ROUND(SUM(Energy_Lost_MW), 2) as Total_Energy_Lost,
    ROUND(SUM(Energy_Lost_MW) / (SELECT SUM(Energy_Lost_MW) FROM AEMR_Outage_Table WHERE Status = 'Approved' AND Outage_Reason = 'Forced') * 100, 2) as Pct_Energy_Lost,
    RANK() OVER (PARTITION BY Participant_Code, Facility_Code ORDER BY SUM(Energy_Lost_MW) DESC) AS rank
FROM
    AEMR_Outage_Table
WHERE
    Participant_Code IN ('GW', 'MELK', 'Auricon') AND Status = 'Approved' AND Outage_Reason = 'Forced'
GROUP BY
    Participant_Code, Facility_Code, Description_Of_Outage
ORDER BY
    Rank ASC, Participant_Code, Total_Energy_Lost DESC

 * sqlite:///AEMR.db
Done.


[('GW', 'BW1_GREENWATERS_G2', 'Operational Issues caused real time forced outage.', 28687.54, 18.84, 1),
 ('MELK', 'MELK_G7', 'Safety Issues', 1100.0, 0.72, 1),
 ('GW', 'BW1_GREENWATERS_G2', 'FO', 833.6, 0.55, 2),
 ('MELK', 'MELK_G7', 'Unit trip - loss of ignition at low load', 972.18, 0.64, 2),
 ('GW', 'BW1_GREENWATERS_G2', 'FO due to unit trip', 473.2, 0.31, 3),
 ('MELK', 'MELK_G7', 'Boiler inspection', 422.22, 0.28, 3),
 ('GW', 'BW1_GREENWATERS_G2', 'Unit failed to start', 353.6, 0.23, 4),
 ('MELK', 'MELK_G7', 'Unit MFT/MTR', 422.0, 0.28, 4),
 ('MELK', 'MELK_G7', 'Boiler Repairs', 422.0, 0.28, 4),
 ('GW', 'BW1_GREENWATERS_G2', 'Unit tripped', 348.4, 0.23, 5),
 ('GW', 'BW1_GREENWATERS_G2', 'Gas Regulation issue', 342.0, 0.22, 6),
 ('MELK', 'MELK_G7', 'Delayed RTS', 416.9, 0.27, 6),
 ('GW', 'BW1_GREENWATERS_G2', 'Kemerton_GT12 tripped on start triggering protection which affected Kemerton_GT11\n', 213.2, 0.14, 7),
 ('GW', 'BW1_GREENWATERS_G2', 'Kemerton_GT12 tripped on start\n', 213.2, 0.14, 7),
 ('MELK', 'MELK_G7', 'Unit MTR.', 411.8, 0.27, 7),
 ('MELK', 'MELK_G7', 'Governor Control Issues.', 411.8, 0.27, 7),
 ('MELK', 'MELK_G7', 'Delayed Unit RTS.', 411.8, 0.27, 7),
 ('GW', 'BW1_GREENWATERS_G2', 'Forced outage', 170.0, 0.11, 9),
 ('GW', 'BW1_GREENWATERS_G2', 'Failed to start', 156.0, 0.1, 10),
 ('GW', 'BW1_GREENWATERS_G2', 'Combustion chamber failed to fire.  Protection Shutdown.', 156.0, 0.1, 10),
 ('MELK', 'MELK_G7', 'Loss off fire to the boiler resulting in pressure drop', 347.26, 0.23, 10),
 ('MELK', 'MELK_G7', 'forced outage due to unit trip', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Unit tripped - LP heater level', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Unit trip due to hydraulic fault', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Rotary air heater wash', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Full forced outage for RAH repairs', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Full forced outage due to unit trip.', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Full forced outage due to boiler feed pump trip', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Forced full outage due to Air Compressor issues', 343.24, 0.23, 11),
 ('MELK', 'MELK_G7', 'Delay in RTS from planned outage', 343.24, 0.23, 11),
 ('GW', 'BW1_GREENWATERS_G2', 'No crane available Furnace 1 & 2. For further information contact Simcoa Furnace Control on 9780 6670', 123.9, 0.08, 12),
 ('GW', 'BW1_GREENWATERS_G2', 'Unit 11 trip on gas detector failure', 103.0, 0.07, 13),
 ('GW', 'BW1_GREENWATERS_G2', 'Operational issue on start up', 98.8, 0.06, 14),
 ('GW', 'BW1_GREENWATERS_G2', 'Kemerton_GT12 tripped on start triggering protection which affected Kemerton_GT11', 98.8, 0.06, 14),
 ('GW', 'BW1_GREENWATERS_G2', 'Furnace 1 unplanned outage', 88.2, 0.06, 16),
 ('GW', 'BW1_GREENWATERS_G2', 'forced outage due to western power ENAR309085', 82.0, 0.05, 17),
 ('GW', 'BW1_GREENWATERS_G2', 'Intertrip from Western Power caused ME breaker 801.1 to open.  Intertrip as a result of a lightning storm in the area.  To be converted to a Consequential Outage.', 82.0, 0.05, 17),
 ('GW', 'BW1_GREENWATERS_G2', 'Ladle car derailment', 58.0, 0.04, 19),
 ('GW', 'BW1_GREENWATERS_G2', 'Oil leak on Ph1', 49.0, 0.03, 20),
 ('MELK', 'MELK_G7', 'Temperature related issues on ramp up', 339.69, 0.22, 20),
 ('GW', 'BW1_GREENWATERS_G2', 'Unit trip on start', 46.8, 0.03, 21),
 ('MELK', 'MELK_G7', 'Partial forced outage due to precip fault', 320.0, 0.21, 21),
 ('GW', 'BW1_GREENWATERS_G2', 'Western Power Trip', 42.0, 0.03, 22),
 ('GW', 'BW1_GREENWATERS_G2', 'Water lines. For further information contact Simcoa Furnace Control on 9780 6670', 42.0, 0.03, 22),
 ('GW', 'BW1_GREENWATERS_G2', 'Remove isolation plates on fan 12. Plant affected, Furnace 1 and 2. \n\nFor further information contact Simcoa Furnace Control on 9780 6670.', 42.0, 0.03, 22),
 ('GW', 'BW1_GREENWATERS_G2', 'No batching, Furnace 1 and 2. For further information contact Simcoa Furnace Control on 9780 6670', 42.0, 0.03, 22),
 ('GW', 'BW1_GREENWATE

<h3 style = "color:#5D3FD3"> Expected Output (Sample) </h3>


 * sqlite:///AEMR.db
Done.


[('AURICON', 'AURICON_PNJ_U1', 'Full unit trip', 6033.87, 3.96, 1),
 ('GW', 'BW1_GREENWATERS_G2', 'Operational Issues caused real time forced outage.', 28687.54, 18.84, 1),
 ('MELK', 'MELK_G7', 'Safety Issues', 1100.0, 0.72, 1)]

Well done! That's a Wrap! We've now analyzed all the data we need to answer Management's Question.
You'll now move to the next part of your analysis where you'll be proceeding with creating your story in Tableau using the insights you've gathered from your SQL Analysis! 

Let's now switch to Part II of our Analysis in Tableau!!

<img src = https://www.energymagazine.com.au/wp-content/uploads/2021/05/shutterstock_1888482466-e1620278098312.jpg>


## Appendix: SQL Cheat Sheet

**SELECT**

```SQL
- SELECT * FROM table_name -- Select all columns from a table
- SELECT column_name(s) FROM table_name -- Select some columns from a table
- SELECT DISTINCT column_name(s) FROM table_name -- Select only the different values
- SELECT column_name(s) FROM table_name -- Select data filtered with the WHERE clause
  WHERE condition
- SELECT column_name(s) FROM table_name -- Order data by multiple columns. DESC for descending 
  ORDER BY column_1, column_2 DESC, column_3 ASC -- and ASC (optional) for ascending order
```

**Operators**
- `<` - Less than
- `>` - Greater than
- `<=` - Less than or equal
- `>=` - Greater than or equal
- `<>` - Not equal
- `=` - Equal
- `BETWEEN v1 AND v2` - Between a specified range
- `LIKE` - Search pattern. Use `%` as a wildcard. E.g., `%o%` matches "o", "bob", "blob", etc.

**Aggregate Functions**
- `AVG(column)` - Returns the average value of a column
- `COUNT(column)` - Returns the number of rows (without a NULL value) of a column
- `MAX(column)` - Returns the maximum value of a column
- `MIN(column)` - Returns the minimum value of a column
- `SUM(column)` - Returns the sum of a column
```SQL
SELECT AVG(column_name), MIN(column_name), MAX(column_name) FROM table_name
```
 
**Miscellaneous**
- `CASE...END` - Used in `SELECT` queries to alter a variable in place. E.g.
```SQL
SELECT column_name
    CASE
        WHEN column_name >= 0 THEN 'POSITIVE'
        ELSE 'NEGATIVE'
    END
FROM table
```
- `AS` - Used to rename a variable. E.g.
```SQL
SELECT SUM(column_name) AS total_column_name FROM table_name
```
- `GROUP BY` - Used to group rows that share the same value(s) in particular column(s). It is mostly used along with aggregation functions
- `ORDER BY` - Determines the order in which the rows are returned by an SQL query